name: hello-world

on: push

jobs:
  hello-world-job: #naming job
    runs-on: ubuntu-latest #github-hosted runner
    steps: 
      - name: checkout repo code
        uses: actions/checkout@3
      - run: echo "$(cat hello_world.txt)"
      
      
    
